name: ci

on:
  push:
    branches:
      - artnoi.com

jobs:
  build:
    name: Build GitHub Pages
    uses: ./github/workflows/pages.yaml
    with:
      sitekey: artnoi.com
      mkdir: ./artnoi.com/dist/fonts
      dist: ./artnoi.com/dist
      deploy_branch: publish/artnoi.com
      wipe_deploy_branch: true
      cname: artnoi.com
    
